### ISSUE TITLE
Create seed data

### ISSUE THREAD

**Issue by vantanova** [cellomatt/aurora#19]
Some data is needed to test our web app.

**Comment by cellomatt** [comment]
Need to update seed data for final project and to include sample "demo_user" for hard-coded demo login.

**Comment by cellomatt** [comment]
Created updated seeders for Topics and Users, including demo_user. 
To Do: Get some good sample questions into the seeder before we deploy.

**Comment by cellomatt** [comment]
Updated sample questions. Could use sample answers and comments.

**Comment by cellomatt** [comment]
Max and I added answer and comment seeds, they're ready to merge. Thanks!
