### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by vantanova** [cellomatt/aurora#2]
1. Will the user enter a username or an email address to login?
* User will login with username

2. What routes should we use for login?

3. Where should the user be redirected after login?

4. What happens if the user doesn't exist yet?

* Display the message "Invalid Login. Sign up here(sign-up page)"

5. What happens if the user enters the wrong password?
* Display the message "Invalid Login"

6. Should this story include allowing a user to reset their password?
* Not yet -- maybe in future story

7. Should logging in use session-based or use token-based authentication?
* session-based

8. How can I log out?
* Once the user is logged in, there will be a logout button that will end the session.

**Comment by cellomatt** [comment]
We finished setting up Login page and user authentication.
