### ISSUE TITLE
Asking a Question

### ISSUE THREAD

**Issue by vantanova** [cellomatt/aurora#5]
1. Where on the site can you ask a question and where do they end up after submission?

* You can ask a question on every page. When you ask a question, you are redirected to the topic page for the topic you selected.

2. What routes do we need?
*

3. Is there a minimum (or maximum) question length?
* No minimum or maximum length

4. How do I tag my question with a topic?
* You select the topic with a dropdown when you write the question

5. How do I tag my question with an experience level?
* You select the experience level with a dropdown when you write the question

6. Can they be deleted?
* Questions can be deleted

7. Can you post an anonymous question?
* Not for MVP

8. How are we going to label who the post belongs to? 
* Label the questions with the username

9. What data do we need to store?
* userId, expertise, topic, title and question body

**Comment by cellomatt** [comment]
We have created a view at /question/new that successfully posts a new question to the /question route. It will redirect to the topic page for the submitted question once we have built out a topics router.

Next steps: Styling

**Comment by cellomatt** [comment]
We also need to implement server-side validation and possibly custom error handling.
