### ISSUE TITLE
Answering a Question

### ISSUE THREAD

**Issue by vantanova** [cellomatt/aurora#6]
1. Can any authorized user answer any question?
* Yes

2. Where can you answer a question?
* On the page for the question

3. What routes do we need to answer a question?
* 

4. How are we going to label who the post belongs to? 
* Label by username

5. Will a user be notified that their question has received an answer (or answers)? 
* Not for MVP

6. Is there a minimum (or maximum) answer length?
* No minimum or maximum length

7. What data do we need to store?
* message, userId, questionId

**Comment by QuintinHull** [comment]
update: we have the functionality working but it needs styling
