### ISSUE TITLE
Commenting on Answers

### ISSUE THREAD

**Issue by vantanova** [cellomatt/aurora#7]
1. Where can you comment on an answer?
* On the question page

2. What routes do we need to post comments?

3. How are we going to label who the comment belongs to? 
* Label by username

4. Will a user be notified that their answer has received a comment? 
* Not for MVP

5. Is there a minimum (or maximum) comment length?
* There is no minimum or maximum comment length

6. What data do we need to store?
* message, answerId, userId

**Comment by QuintinHull** [comment]
update: we have the functionality working but it needs styling
